# This is a basic workflow to help you get started with Actions

name: create-small-images
run-name: Image Generation

# Controls when the workflow will run
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create-images:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      
      - name: generate-small-card-images
        run: .github/workflows/scripts/generate-small-card-images.sh
        
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
